name: CI-Polaris-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: 21
            architecture: x64  
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        with:
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SCA,SAST"
          polaris_prComment_enabled: true
          github_token: ${{ secrets.GH_TOKEN }}

          polaris_application_name: "black-duck-hugo-demo"
          polaris_project_name: "webgoat"
